### ISSUE TITLE
downloading results 

### ISSUE THREAD

**Issue by Oelsakha** [jetstream-cloud/js2docs#35]
Hi all 
I want to download my files after I finished my work. Unfortunately, I have more than 3000 file to download. 
Do you know the easiest way to download these files?

Thank you

**Comment by jlf599** [comment]
If this is a request for help using Jetstream2, please contact help@jetstream-cloud.org or use https://jetstream-cloud.org/contact/index.html

**Comment by Oelsakha** [comment]
Thank you. I will do.
