### ISSUE TITLE
Problem: exouser will no longer be the primary account used to access Exosphere instances

### ISSUE THREAD

**Issue by julianpistorius** [jetstream-cloud/js2docs#51]
The upcoming Exosphere merge request (https://gitlab.com/exosphere/exosphere/-/merge_requests/793) will introduce a change in which the primary user on Exosphere-launched instances will become the user's ACCESS-CI username, instead of the default `exouser`. However, `exouser` will still work as an additional username.

To ensure that the Jetstream 2 documentation remains accurate and up-to-date, we need to update the relevant sections to reflect these changes. Please review the following occurrences of `exouser` in the documentation and address appropriately:

https://github.com/search?q=repo%3Ajetstream-cloud%2Fjs2docs%20exouser&type=code

For reference, please review the following links:

- Exosphere merge request that will introduce the change: https://gitlab.com/exosphere/exosphere/-/merge_requests/793
- Exosphere issue that justified the change: https://gitlab.com/exosphere/exosphere/-/issues/354

**Comment by c-mart** [comment]
I don't think https://gitlab.com/exosphere/exosphere/-/merge_requests/793 is mergeable with the current design; I suggest taking no action on a solution toward this until we evolve that design.
