### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by c-mart** [jetstream-cloud/js2docs#71]
The site doesn't have an appropriate favicon. This will be shown in search engine results too. Can steal from here: https://gitlab.com/exosphere/exosphere/-/blob/master/assets/img/jetstream2-favicon.ico?ref_type=heads

**Comment by jlf599** [comment]
Weird. We had one and now it's commented out

#site_favicon: 'images/Jetstream2_icon_64px.jpg'

Not sure why.

**Comment by jlf599** [comment]
Oh:

Back in version 0.16.0, the site_favicon configuration setting was deprecated. Then in version 0.17.0 is was completely removed. Therefore, your config is doing nothing.

So it can just dropped in.

**Comment by jlf599** [comment]
Fixed.

**Comment by jlf599** [comment]
fixed
