### ISSUE TITLE
Need to specify project ID when creating S3 credentials

### ISSUE THREAD

**Issue by manning-ncsa** [jetstream-cloud/js2docs#72]
The instructions for creating credentials to access the S3-compatible API at https://github.com/jetstream-cloud/js2docs/blob/570a4b27569514133d143baf077f9e542a72ab87/docs/general/s3.md?plain=1#L15 should consider including the `--project` option. I was unable to create credentials without including my OpenStack project ID like so:

```
openstack ec2 credentials create --project 30d6f2f7cc3a878a7547e319abf0687a
```

(Note that `30d6f2f7cc3a878a7547e319abf0687a` is a fake project ID.) 

This was likely due to the fact that I sourced an openrc file downloaded from an application credential instead of the primary account OpenStack RC file from `https://js2.jetstream-cloud.org/project/api_access/openrc/`. Either way, it might save someone confusion.

**Comment by zacharygraber** [comment]
@manning-ncsa Thanks for the notice! I'm personally unable to reproduce this, though. V3 application credentials (what's used on Jetstream2) are tied to a specific project, and `openstack ec2 credentials create` should default to the currently authenticated project (i.e., the one tied to your app cred):

```
  --project <project>
      Create credentials in project (name or ID; default: current authenticated project)
```

Does `openstack ec2 credentials create` without a `--project` flag give you a specific error message? If so, could you share it, along with the output of `openstack --version`? That might help determine what situations this applies to.

**Comment by manning-ncsa** [comment]
1. Navigate to https://js2.jetstream-cloud.org/identity/application_credentials/.
2. Click Create Application Credential
3. Make a name `test-temp` and click okay
4. Click "Download openrc file": `app-cred-test-temp-openrc.sh`
   ```
   #!/usr/bin/env bash
   
   export OS_AUTH_TYPE=v3applicationcredential
   export OS_AUTH_URL=https://js2.jetstream-cloud.org:5000/v3/
   export OS_IDENTITY_API_VERSION=3
   export OS_REGION_NAME="IU"
   export OS_INTERFACE=public
   export OS_APPLICATION_CREDENTIAL_ID=14...0a
   export OS_APPLICATION_CREDENTIAL_SECRET=mNt...6g
   ```

Here are some commands I tried just now, using v5.8.0 of the OpenStack client. Afterward I updated to the latest v6.5.0 by forcing the version (`pip install python-openstackclient==6.5.0`), but the results were the same.

```
$ source app-cred-test-temp-openrc.sh 

$ env | grep OS_
OS_REGION_NAME=IU
OS_INTERFACE=public
OS_AUTH_URL=https://js2.jetstream-cloud.org:5000/v3/
OS_APPLICATION_CREDENTIAL_SECRET=mN...6g
OS_APPLICATION_CREDENTIAL_ID=14...0a
OS_AUTH_TYPE=v3applicationcredential
OS_IDENTITY_API_VERSION=3

$ openstack --version
openstack 5.8.0

$ openstack ec2 credentials list
Internal Server Error (HTTP 500)

$ openstack ec2 credentials create --verbose
START with options: ec2 credentials create --verbose
command: ec2 credentials create -> openstackclient.identity.v3.ec2creds.CreateEC2Creds (auth=True)
Using auth plugin: v3applicationcredential
Internal Server Error (HTTP 500)
END return value: 1

$ openstack ec2 credentials create --verbose --project bec5e8e5bd504eee9b9a81dad5d45c72
START with options: ec2 credentials create --verbose --project bec5e8e5bd504eee9b9a81dad5d45c72
command: ec2 credentials create -> openstackclient.identity.v3.ec2creds.CreateEC2Creds (auth=True)
Using auth plugin: v3applicationcredential
Internal Server Error (HTTP 500)
END return value: 1

$ openstack application credential list 
+----------------------------------+-----------+----------------------------------+-------------+------------+
| ID                               | Name      | Project ID                       | Description | Expires At |
+----------------------------------+-----------+----------------------------------+-------------+------------+
| 14a56666b102483faaed72f7962b290a | test-temp | bec5e8e5bd504eee9b9a81dad5d45c72 | None        | None       |
+----------------------------------+-----------+----------------------------------+-------------+------------+

$ openstack application credential show 14a56666b102483faaed72f7962b290a
+--------------+----------------------------------+
| Field        | Value                            |
+--------------+----------------------------------+
| description  | None                             |
| expires_at   | None                             |
| id           | 14a56666b102483faaed72f7962b290a |
| name         | test-temp                        |
| project_id   | bec5e8e5bd504eee9b9a81dad5d45c72 |
| roles        | reader member                    |
| system       | None                             |
| unrestricted | False                            |
| user_id      | b3d7bb102c9c42279c81d5dc9d5d918f |
+--------------+----------------------------------+
```

**Comment by zacharygraber** [comment]
@manning-ncsa I believe this is actually an issue with our backend infrastructure, and not with the way the docs are written. Usually, openstack calls are load-balanced, meaning that if one (of 2+) handlers are misbehaving, your call may or may not succeed depending on which one you arrive at.

For example, if I spam `openstack ec2 credentials list` over and over again, ~50% of the time it works, and the other half it doesn't (depending on how unlucky I am).

I opened an [issue in our infrastructure/project management space](https://gitlab.com/jetstream-cloud/project-mgt/-/issues/170) to track this.
